### ISSUE TITLE
'SonarAnalyzer.Rules.CSharp.UnusedPrivateMember' threw an exception of type 'System.ArgumentOutOfRangeException'

### ISSUE THREAD

**Issue by dibley1973** [SonarSource/sonarlint-visualstudio#1010]
### Description

When building solution using Visual Studio 2015 Professional and SonarLint I have just started experiencing the following error `Warning	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.UnusedPrivateMember' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.
Parameter name: lineNumber'.`

Full error is:

```
Severity	Code	Description	Project	File	Line	Category	Suppression State	Detail Description
Warning	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.UnusedPrivateMember' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Specified argument was out of the range of valid values.
Parameter name: lineNumber'.
Analyzer 'SonarAnalyzer.Rules.CSharp.UnusedPrivateMember' threw the following exception:
'Exception occurred with following context:
Compilation: [MyClassName/OrProjectName?]
ISymbol: [MyClassName](NamedType)

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: lineNumber
   at Microsoft.VisualStudio.Text.Implementation.SimpleStringRebuilder.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetLineFromLineNumber(Int32 lineNumber)
   at Microsoft.CodeAnalysis.Text.Extensions.SnapshotSourceText.LineInfo.get_Item(Int32 index)
   at SonarLint.VisualStudio.Integration.Vsix.Suppression.LiveIssueFactory.Create(SyntaxTree syntaxTree, Diagnostic diagnostic)
   at SonarLint.VisualStudio.Integration.Vsix.Suppression.SuppressionHandler.ShouldIssueBeReported(SyntaxTree syntaxTree, Diagnostic diagnostic)
   at SonarLint.VisualStudio.Integration.Vsix.SonarAnalyzerConnectedWorkflow.VsixAnalyzerReportDiagnostic(IReportingContext context)
   at SonarAnalyzer.Helpers.AnalysisContextExtensions.ReportDiagnostic(ReportingContext reportingContext)
   at SonarAnalyzer.Rules.CSharp.UnusedPrivateMember.<>c__DisplayClass7_0.<Initialize>b__1(SymbolAnalysisContext cc)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass37_0.<ExecuteSymbolActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
```
This is for a C# project

### Repro steps

1. Press <kbd>SHIFT</kbd>+<kbd>CTRL</kbd>+<kbd>B</kbd> to do a full solution rebuild

2. Observe WARNING in `Error List` window.

If possible then please create a git repository with a repro sample or attach a zip to the issue.

### Expected behavior

Not to throw the exception

### Actual behavior

After building the solution, the true static analysis warning should display, not detail of an exception thrown.

### Known workarounds

None known.

### Related information

* SonarLint for VS Version: 4.9.0.4316
* Visual Studio Version : Professional v14.0.25431.01 Update 3)
* SonarQube server version: Not known.
* Languages in your solution: C#, Powershell

**Comment by duncanp-sonar** [comment]
@dibley1973 thanks for reporting the issue.

I haven't managed to repro the issue locally so far. I could just put a try-catch round the appropriate block of code, but if possible I'd like to understand the circumstances in which occurs so I can make a more targeted fix.

A couple of questions:
1) are you using connected mode?
2) how frequently does this warning appear?
3) were you editing the file when the error occurred? (or to put it another was, does it appear in files that haven't been edited?)

Thanks.
