### ISSUE TITLE
Exception w/Arduino (Sketch .ino files).

### ISSUE THREAD

**Issue by davegi** [SonarSource/sonarlint-visualstudio#1298]
### Description

Opening 'sketch' projects causes the following exception in the SonarLint Output window.

### Repro steps

Open Arduino/sketch based project.

### Expected behavior

No exception. Normal SonarLint behavior. 😎

### Actual behavior

Using default daemon download URL
Daemon version: 4.3.2.2521
Daemon download url: https://binaries.sonarsource.com/Distribution/sonarlint-daemon/sonarlint-daemon-4.3.2.2521-windows.zip
Loaded settings from "C:\Users\daveg\AppData\Roaming\SonarLint for Visual Studio\settings.json".
Unable to collect C/C++ configuration for D:\OneDrive\Documents\Arduino\My Examples\ssd1306_128x64_i2c\ssd1306_128x64_i2c.ino: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.VisualStudio.ProjectSystem.ProjectException: The "ConfigurationCustomBuildTool" rule is missing the "AdditionalIncludeDirectories" property.
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorUtilities.ThrowProjectExceptionHelper(Exception innerException, String unformattedMessage, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorUtilities.ThrowProjectException(String message, Object arg0, Object arg1)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorUtilities.ThrowRulePropertyMissing(ConfiguredProject configuredProject, String ruleName, String propertyName, String fileName, String itemType, String itemName)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCRulePropertyStorage.<>c__DisplayClass5_0.<<GetEvaluatedPropertyValue>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.ApartmentMarshaler.<>c__DisplayClass9_0`1.<<Invoke>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.ApartmentMarshaler.Invoke[TResult](Func`1 method)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCRulePropertyStorage.GetEvaluatedPropertyValue(String propertyName)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCToolBase.Microsoft.VisualStudio.VCProjectEngine.IVCRulePropertyStorage.GetEvaluatedPropertyValue(String propertyName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.FileConfig.GetEvaluatedPropertyValue(Object fileTool, String propertyName)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.FileConfig.TryGet(ProjectItem projectItem, String absoluteFilePath)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.TryGetConfig(ILogger logger, ProjectItem projectItem, String absoluteFilePath)
Initializing the telemetry package...
Finished initializing the telemetry package...
Initializing the notifications package...
Not connected: not checking for notifications
Finished initializing the notifications package
Cannot analyze header files. File: 'C:\Users\daveg\AppData\Local\arduino15\packages\esp8266\hardware\esp8266\2.6.3\cores\esp8266\Arduino.h'
Cannot analyze header files. File: 'D:\OneDrive\Documents\Arduino\libraries\Adafruit_GFX_Library\Adafruit_GFX.h'
Initializing the daemon package...
Finished initializing the daemon package.

### Known workarounds

None.

### Related information

VS Community 2019 w/SonarLint etc., all up-to-date.

**Comment by duncanp-sonar** [comment]
@davegi which third-party extension for Arduino are you using - [Arduino IDE for Visual Studio](https://marketplace.visualstudio.com/items?itemName=VisualMicro.ArduinoIDEforVisualStudio)?

**Comment by davegi** [comment]
[Arduino IDE for Visual Studio (Visual Micro) - Visual Studio Marketplace](https://tmpl.at/3dYUg4P)
________________________________

**Comment by duncanp-sonar** [comment]
@davegi I can repro the bug. However, I'm not sure we can easily add support for Arduino projects.

There seem to be a couple of Arduino project types, one of which layers additional behaviours on top of a "normal" `.vcxproj`, and a `vcxitems` project type that isn't.

To provide accurate results, our C/C++ analyser needs to capture all of the many configuration parameters that are passed to the compiler i.e. lots of the data from the standard C++ project properties:

![image](https://user-images.githubusercontent.com/10757559/78911915-e5e9e380-7a7e-11ea-9b39-51acde4dda0f.png)

These property pages are still available for Arduino projects, but many of the properties are missing. In addition, there appear to be a specific set of extra project properties for Sketch projects that will affect the flags that are passed to the compiler:

![image](https://user-images.githubusercontent.com/10757559/78912220-3c572200-7a7f-11ea-8b53-3b6365f529ee.png)

Are both the settings in the "normal" C++ project properties and Sketch-specific properties used?

**Comment by davegi** [comment]
I am fairly new to Arduino/sketch development but I believe both sets of Properties are used. The author of [Arduino for Visual Studio](https://www.visualmicro.com/) suggested that I look at [Arduino - Software](https://www.arduino.cc/en/Main/Software) to fully understand sketch development. He's also a very approachable gent who I suspect will be happy to help if you approach him directly.
Thanks,
djg

________________________________

**Comment by duncanp-sonar** [comment]
Thanks for the info @davegi. We were looking at handling this issue as bug fix, but now it looks more like a new feature in terms of the amount of work required.

Given that, I'm afraid to say that it's very unlikely we'll add support for Arduino projects in SonarLint unless there is enough demand. With our current resources, adding support for CMake projects (#903) would be higher priority they are supported out of the box in VS2019 and are widely used.

If you feel strongly that Arduino projects should be supported in SonarLint, please suggest it as a [new feature](https://community.sonarsource.com/c/suggestions/features/14) in the community forum so other users can vote on it.

Have you tried analysing Arduino projects in SonarQube/SonarCloud using the [CFamily build wrapper](https://docs.sonarqube.org/latest/analysis/languages/cfamily/) so you can at least see issues in SonarQube/SonarCloud?
