### ISSUE TITLE
Analysis fails and exception is thrown on FIPS-enabled machines

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#1533]
### Description

Enabling FIPS causes SLVS to throw an exception and not analyze the files. [Raised by the community](https://community.sonarsource.com/t/sonarlint-in-visual-studio-2019-fails-to-analyse-c-files-system-invalidoperationexception-this-implementation-is-not-part-of-the-windows-platform-fips-validated-cryptographic-algorithms/28075).
The issue is caused due to usage of MD5 algorithm to match analysis issues to server suppressions. 

### Repro steps

1. [Enable FIPS](https://docs.vmware.com/en/VMware-Horizon-Client-for-Windows/5.4/horizon-client-windows-installation/GUID-D4238105-E533-4518-A521-B82B49D86585.html#:~:text=To%20use%20the%20group%20policy,%2C%20hashing%2C%20and%20signing%20setting.) 

2. Analyze a file

### Expected behavior

Analysis succeeds.

### Actual behavior

An exception is thrown

```
Loaded settings from "C:\path\to\.sonarlint\myprojectkey_cpp_settings.json".
Using connected mode settings. User-specified settings in settings.json will be ignored.
Calculating effective rule settings...
Note: the following CFamily rules are not available in SonarLint: cpp:S5536, c:S5536, cpp:S5801, c:S5801, cpp:S5814, c:S5814, cpp:S5815, c:S5815, cpp:S5816, c:S5816, cpp:S5824, c:S5824
Analyzing C:\path\to\MyFile.cpp
Failed to analyze C:\path\to\MyFile.cpp, exception details: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at SonarLint.VisualStudio.Integration.Suppression.ChecksumCalculator.Calculate(String text)
   at SonarLint.VisualStudio.Integration.Vsix.IssueToIssueMarkerConverter.Convert(IAnalysisIssue issue, ITextSnapshot textSnapshot)
   at SonarLint.VisualStudio.Integration.Vsix.AccumulatingIssueConsumer.<Accept>b__8_0(IAnalysisIssue x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SonarLint.VisualStudio.Integration.Vsix.AccumulatingIssueConsumer.Accept(String path, IEnumerable`1 issues)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CLangAnalyzer.HandleMessage(Message message, Request request, IIssueConsumer consumer, Int32& issueCount)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CLangAnalyzer.<>c__DisplayClass12_0.<TriggerAnalysisAsync>b__0(Message message)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.Protocol.Read(BinaryReader reader, Action`1 handleIssue, String issueFilePath)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.<>c__DisplayClass8_1.<CallClangAnalyzer>b__1(StreamReader reader)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.ProcessRunner.Execute(ProcessRunnerArguments runnerArgs)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.CallClangAnalyzer(Action`1 handleMessage, Request request, IProcessRunner runner, IAnalysisStatusNotifier statusNotifier, ILogger logger, CancellationToken cancellationToken)
Found 1 issue(s) for C:\path\to\MyFile.cpp
ERROR: LLVM ERROR: IO failure on output stream: invalid argument
Checking for suppressions...
Number of suppressions found: 0
```

### Known workarounds

Option 1 - [Disable FIPS on the machine](https://docs.trendmicro.com/all/ent/sc/v3.0/en-US/cmcolh/t_fips.html#:~:text=In%20Security%20Settings%2C%20expand%20Local,signing%2C%20and%20then%20click%20Disabled.).
Option 2 - [Disable FIPS exception](https://docs.microsoft.com/en-us/archive/blogs/shawnfa/disabling-the-fips-algorithm-check) in Visual Studio's[ `devenv.exe.config`](https://www.google.com/search?q=where%20is%20devenv.exe.config%20visual%20studio). _Note: this might be a repeating action, as `devenv.exe.config` is being overwritten when VS is updated._

### Related information

* SonarLint for VS Version v4.23.0.19399
* Visual Studio Professional 2019 (v16.6.3) 
* Languages in the solution: C++

**Comment by cacti77** [comment]
I can confirm this is fixed in SonarlInt 4.24.0.20196 in Visual Studio Pro 2019 v16.6.5 (I reported the original issue [here](https://community.sonarsource.com/t/sonarlint-in-visual-studio-2019-fails-to-analyse-c-files-system-invalidoperationexception-this-implementation-is-not-part-of-the-windows-platform-fips-validated-cryptographic-algorithms/28075)).
