### ISSUE TITLE
Unable to collect C/C++ configuration in MakeFile-project

### ISSUE THREAD

**Issue by Wastus** [SonarSource/sonarlint-visualstudio#1546]
### Description

In a MakeFile-project SonarLint is unable to collect the C/C++ configuration (naturally, it is stored inside some external file).

### Repro steps

1. Create a MakeFile-project

2. Create a class and open the .cpp file

[Project1.zip](https://github.com/SonarSource/sonarlint-visualstudio/files/5000020/Project1.zip)

### Expected behavior

At first I expected it just to work (i.e. use some default values which probably work for a lot of cases). After thinking about it, MakeFile-projects could likely target other platforms (embedded in my case) which have some special properties like different integer sizes.

So I guess in this case it would be best to have an option to provide a configuration file which allows setting up a custom C/C++ configuration.

### Actual behavior

I only get these exceptions:

> Unable to collect C/C++ configuration for C:\temp\Project1\Test.cpp: System.InvalidOperationException: Cannot query for a file configuration tool for an MakeFile project.
>    at Microsoft.Verify.FailOperation(String message, Object[] args)
>    at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCFileConfigurationShim.<<get_Tool>b__20_0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.ApartmentMarshaler.<>c__DisplayClass9_0`1.<<Invoke>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
>    at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
>    at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
>    at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
>    at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.ApartmentMarshaler.Invoke[TResult](Func`1 method)
>    at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCFileConfigurationShim.get_Tool()
>    at CallSite.Target(Closure , CallSite , Object )
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
>    at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.FileConfig.TryGet(ProjectItem projectItem, String absoluteFilePath)
>    at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.TryGetConfig(ILogger logger, ProjectItem projectItem, String absoluteFilePath)

### Known workarounds

None

### Related information

* SonarLint for VS Version 4.23.0.19399
* Visual Studio Version Professional v19.6.5
* SonarQube server version: none, standalone SonarLint
* Languages in your solution: C++

**Comment by pavel-mikula-sonarsource** [comment]
Moved to [SLVS-2279](https://sonarsource.atlassian.net/browse/SLVS-2279)

[SLVS-2279]: https://sonarsource.atlassian.net/browse/SLVS-2279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
