### ISSUE TITLE
Debug exception is thrown when taint vulnerability's file cannot be found locally

### ISSUE THREAD

**Issue by rita-g-sonarsource** [SonarSource/sonarlint-visualstudio#2066]
Steps to reproduce:

1. Open a solution that is bound to a project with taint vulnerabilities
2. Unload the project/remove the files where the vulnerability occurs
3. Open the taint list

Expected ==> No exception
Actual ==> Debug exception

```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: path
  Source=mscorlib
  StackTrace:
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Path.GetFullPath(String path)
   at SonarLint.VisualStudio.Core.Helpers.PathHelper.IsMatchingPath(String path1, String path2) in C:\Projects\SLVS\sonarlint-visualstudio\src\Core\Helpers\PathHelper.cs:line 145
   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintList.ViewModels.TaintIssuesControlViewModel.ActiveDocumentFilter(Object viewModel) in C:\Projects\SLVS\sonarlint-visualstudio\src\IssueViz.Security\Taint\TaintList\ViewModels\TaintIssuesControlViewModel.cs:line 116
   at System.Windows.Data.ListCollectionView.PrepareLocalArray()
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.RefreshOrDefer()
   at System.Windows.Data.CollectionView.set_Filter(Predicate`1 value)
   at System.Windows.Data.ListCollectionView.set_Filter(Predicate`1 value)
   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintList.ViewModels.TaintIssuesControlViewModel.ApplyViewFilter(Predicate`1 filter) in C:\Projects\SLVS\sonarlint-visualstudio\src\IssueViz.Security\Taint\TaintList\ViewModels\TaintIssuesControlViewModel.cs:line 104
   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintList.ViewModels.TaintIssuesControlViewModel..ctor(ITaintStore store, ILocationNavigator locationNavigator, IActiveDocumentTracker activeDocumentTracker, IActiveDocumentLocator activeDocumentLocator, IShowInBrowserService showInBrowserService) in C:\Projects\SLVS\sonarlint-visualstudio\src\IssueViz.Security\Taint\TaintList\ViewModels\TaintIssuesControlViewModel.cs:line 91
   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintList.TaintToolWindow..ctor(IServiceProvider serviceProvider) in C:\Projects\SLVS\sonarlint-visualstudio\src\IssueViz.Security\Taint\TaintList\TaintToolWindow.cs:line 45
   at SonarLint.VisualStudio.IssueVisualization.Security.IssueVizSecurityPackage.InstantiateToolWindow(Type toolWindowType) in C:\Projects\SLVS\sonarlint-visualstudio\src\IssueViz.Security\IssueVizSecurityPackage.cs:line 88
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, ProvideToolWindowAttribute tool)
   at Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Guid& toolWindowType, Int32 id)
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsToolWindowFactory.CreateToolWindow(Guid& toolWindowType, UInt32 id)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateFrame(String moniker, UInt32 instanceID, IVsWindowFrame& frame)

  This exception was originally thrown at this call stack:
    System.IO.Path.GetFullPathInternal(string)
    System.IO.Path.GetFullPath(string)
    SonarLint.VisualStudio.Core.Helpers.PathHelper.IsMatchingPath(string, string) in PathHelper.cs
    SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintList.ViewModels.TaintIssuesControlViewModel.ActiveDocumentFilter(object) in TaintIssuesControlViewModel.cs
    System.Windows.Data.ListCollectionView.PrepareLocalArray()
    System.Windows.Data.ListCollectionView.RefreshOverride()
    System.Windows.Data.CollectionView.RefreshInternal()
    System.Windows.Data.CollectionView.RefreshOrDefer()
    System.Windows.Data.CollectionView.Filter.set(System.Predicate<object>)
    System.Windows.Data.ListCollectionView.Filter.set(System.Predicate<object>)
    ...
    [Call Stack Truncated]
```

**Comment by duncanp-sonar** [comment]
@rita-g-sonarsource what does "debug exception" mean?
One that's only thrown in debug builds, or one that is thrown in the background and silently swallowed so it won't cause a crash?

**Comment by rita-g-sonarsource** [comment]
> @rita-g-sonarsource what does "debug exception" mean?
> One that's only thrown in debug builds, or one that is thrown in the background and silently swallowed so it won't cause a crash?

Thrown in the background, doesn't cause a crash.
