### ISSUE TITLE
CFamily analysis fails when file has mixed line endings (CRLF and LF)

### ISSUE THREAD

**Issue by rita-sonarsource** [SonarSource/sonarlint-visualstudio#2276]
### Description

When a CFamily file (C, C++, .h) contains mixed line endings (CRLF and LF), the analysis fails:

```
Failed to analyze C:\Users\michal\source\repos\Project3\Project3\Source1.cpp, exception details: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Text.SnapshotSpan.TranslateTo(ITextSnapshot targetSnapshot, SpanTrackingMode spanTrackingMode)
   at SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.<>c__DisplayClass22_0.<TranslateSpans>b__1(IAnalysisIssueVisualization x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.TranslateSpans(IEnumerable`1 issues, ITextSnapshot activeSnapshot)
   at SonarLint.VisualStudio.Integration.Vsix.TextBufferIssueTracker.HandleNewIssues(IEnumerable`1 issues)
   at SonarLint.VisualStudio.Integration.Vsix.AccumulatingIssueConsumer.Accept(String path, IEnumerable`1 issues)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CLangAnalyzer.HandleMessage(Message message, Request request, IIssueConsumer consumer, Int32& issueCount)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CLangAnalyzer.<>c__DisplayClass14_0.<TriggerAnalysisAsync>b__1(Message message)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.Protocol.Read(BinaryReader reader, Action`1 handleIssue, String issueFilePath)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.<>c__DisplayClass23_0.<CallClangAnalyzer>b__1(StreamReader reader)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.ProcessRunner.Execute(ProcessRunnerArguments runnerArgs)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyHelper.CallClangAnalyzer(Action`1 handleMessage, Request request, IProcessRunner runner, ILogger logger, CancellationToken cancellationToken)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CLangAnalyzer.CallSubProcess(Action`1 handleMessage, Request request, ISonarLintSettings settings, ILogger logger, CancellationToken cancellationToken)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CLangAnalyzer.<TriggerAnalysisAsync>d__14.MoveNext()
ERROR: LLVM ERROR: IO failure on output stream: invalid argument
```

#### Workaround
Fixing the line endings to CRLF fixes the problem.

#### Repro project
[Project3 (1).zip](https://github.com/SonarSource/sonarlint-visualstudio/files/6237077/Project3.1.zip)

#### Notes
There are 2 separate problems that cause this issue:
1. [LineHashCalculator](https://github.com/SonarSource/sonarlint-visualstudio/blob/6b9a8a7623906def168229d9089bf6e17a9c00a4/src/IssueViz/Editor/LineHashCalculator.cs#L76) splits lines according to CRLF only, which causes the hash to be incorrect if the hashed line is followed by a LF end line. [IIssueSpanCalculator](https://github.com/SonarSource/sonarlint-visualstudio/blob/6b9a8a7623906def168229d9089bf6e17a9c00a4/src/IssueViz/Editor/IIssueSpanCalculator.cs#L68) then returns an empty span due to the hashes being different (as VS is able to split the lines correctly).
2. [TextBufferIssueTracker](https://github.com/SonarSource/sonarlint-visualstudio/blob/f1a2d46fd631512efa19797139872e821f05226e/src/Integration.Vsix/SonarLintTagger/TextBufferIssueTracker.cs#L122) doesn't take into account that the returned span could be empty, which causes the reported exception.

TODO:
- [ ] Fix TextBufferIssueTracker to ignore empty spans
- [ ] Fix LineHashCalculator to split the lines accordingly

**Comment by abbas-sabra-sonarsource** [comment]
@rita-sonarsource I'm constantly facing a similar issue it has the same call stack and it sounds related but I'm not sure if it is exactly the same as the one you described.

Here is a reproducer that might help:
analyze a file with this content:
```
typedef unsigned long long A;
const char a[] = "aabbcc";
```
- It only fails when LF is used(not mixed).
- It only fails if it is on the first line. adding a new line at the begging fixes the issue.
