### ISSUE TITLE
Exception is shown in the output window when a compatible node version could not be found 

### ISSUE THREAD

**Issue by rita-sonarsource** [SonarSource/sonarlint-visualstudio#2459]
#### Description

When we fail to find a compatible node.exe version, a message is written to the output log: `[NodeJsLocator] Could not find a compatible node version. Supported versions are v10 and v12+.`
However, the message is then followed by an ugly stack trace:
```
Failed to analyze C:\Projects\sonarlint-vscode\src\client.ts: System.IO.FileNotFoundException: Could not find node.exe
   at SonarLint.VisualStudio.TypeScript.EslintBridgeClient.EslintBridgeProcess.FindNodePath()
   at SonarLint.VisualStudio.TypeScript.EslintBridgeClient.EslintBridgeProcess.StartServer()
   at SonarLint.VisualStudio.TypeScript.EslintBridgeClient.EslintBridgeProcess.Start()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.EslintBridgeClient.EslintBridgeClient.<MakeCall>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.EslintBridgeClient.TypeScriptEslintBridgeClient.<TsConfigFiles>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.TsConfig.TsConfigProvider.<GetConfigForFile>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.TsConfig.TsConfigProvider.<GetConfigForFile>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.Analyzer.TypeScriptAnalyzer.<ExecuteAnalysis>d__8.MoveNext()
```

Notes:
* This happens in VS2015, as other VS versions come bundled with a compatible node version.

TODO:
- [ ] Don't show the stack trace

**Comment by duncanp-sonar** [comment]
Duplicate of #2542

**Comment by rita-sonarsource** [comment]
Closing as dup of #2452
