### ISSUE TITLE
FileNotFoundException is thrown when analysis is invoked on temporary build files

### ISSUE THREAD

**Issue by rita-sonarsource** [SonarSource/sonarlint-visualstudio#2696]
#### Description

When opening a project for the first time, an exception is thrown:

```
Failed to analyze Temp.txt: System.IO.FileNotFoundException: Could not find file 'C:\Projects\sonarlint-visualstudio\src\Integration.Vsix\bin\Debug\VS2019\net46\Temp.txt'.
File name: 'C:\Projects\sonarlint-visualstudio\src\Integration.Vsix\bin\Debug\VS2019\net46\Temp.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.VisualStudio.Text.Implementation.TextDocumentFactoryService.OpenFileGuts(String filePath, DateTime& lastModifiedTimeUtc, Int64& fileSize)
   at Microsoft.VisualStudio.Text.Implementation.TextDocumentFactoryService.OpenFile(String filePath, DateTime& lastModifiedTimeUtc, Int64& fileSize)
   at Microsoft.VisualStudio.Text.Implementation.TextDocumentFactoryService.CreateAndLoadTextDocument(String filePath, IContentType contentType, Boolean attemptUtf8Detection, Boolean allowCompressedStorage, Boolean throwOnInvalidCharactersIfUnknownEncoding, Boolean& characterSubstitutionsOccurred)
   at Microsoft.VisualStudio.Text.Implementation.TextDocumentFactoryService.CreateAndLoadTextDocument(String filePath, IContentType contentType)
   at SonarLint.VisualStudio.CloudSecrets.SecretsAnalyzer.ExecuteAnalysis(String filePath, String charset, IEnumerable`1 detectedLanguages, IIssueConsumer consumer, IAnalyzerOptions analyzerOptions, CancellationToken cancellationToken)
```

TODO:
- [x] Check if there is a way not to invoke analysis on temp files
- [ ] Verify that the file exists before attempting to read it

**Comment by rita-sonarsource** [comment]
Happens with latest master build 6.8
