### ISSUE TITLE
The plugin throw an exception when I open a c++ project

### ISSUE THREAD

**Issue by leekerberos** [SonarSource/sonarlint-visualstudio#273]
![image](https://user-images.githubusercontent.com/12462173/30416394-8a03786e-995e-11e7-8e22-7b364b607514.png)
It seems some configurations are not correct. Details are shown below.

`Unable to collect C/C++ configuration: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.VisualStudio.ProjectSystem.ProjectException: The "ConfigurationCustomBuildTool" rule is missing the "AdditionalIncludeDirectories" property.
   at Microsoft.VisualStudio.ProjectSystem.Utilities.ProjectErrorUtilities.ThrowProjectExceptionHelper(Exception innerException, String unformattedMessage, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.ProjectErrorUtilities.ThrowProjectException(String message, Object arg0, Object arg1)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCRulePropertyStorage.<>c__DisplayClass5_0.<<GetEvaluatedPropertyValue>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.ApartmentMarshaler.<>c__DisplayClass9_0`1.<<Invoke>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.ApartmentMarshaler.Invoke[TResult](Func`1 method)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCRulePropertyStorage.GetEvaluatedPropertyValue(String propertyName)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCToolBase.Microsoft.VisualStudio.VCProjectEngine.IVCRulePropertyStorage.GetEvaluatedPropertyValue(String propertyName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CallSite.Target(Closure , CallSite , MethodInfo , Object , Object[] )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.FileConfig.GetEvaluatedPropertyValue(Object fileTool, String propertyName)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.FileConfig.TryGet(ProjectItem projectItem, String absoluteFilePath)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.TryGetConfig(ProjectItem projectItem, String absoluteFilePath, String& sqLanguage)`

**Comment by leekerberos** [comment]
I found the problem may locate here.(See picture below) And I think it's a bug in sonarlint.
![image](https://user-images.githubusercontent.com/12462173/30423001-1bea0ed6-9974-11e7-9af3-efa30da178a5.png)
In fact I was using sonarlint to analyze chromium project. And it use 'GN' as build tool. Projects generated by 'GN' use custom project configuration named 'GN' which is different from 'Debug' or 'Realse' in normal c++ project. So sonarlint can not read properties from the configuration correctly.

**Comment by leekerberos** [comment]
I have found a  fast solution -- hard coding all the configuration properties. Though it seems stupid, it can solve my problem.
