### ISSUE TITLE
NRE after startup: The 'SonarLintIntegrationPackage' package did not load correctly

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonarlint-visualstudio#2736]
### Version

SL 4.39.0.38793 DOGFOOD
VS 2019 16.11.4

### Description

Error message appears after VS startup:
The 'SonarLintIntegrationPackage' package did not load correctly 

### ActivityLog

```
SetSite failed for package [SonarLintIntegrationPackage]
Source: 'SonarLint.2019' 
Description: Object reference not set to an instance of an object. 
System.NullReferenceException: Object reference not set to an instance of an object.
at SonarLint.VisualStudio.Integration.Vsix.SonarLintIntegrationPackage.<InitOnUIThreadAsync>d__5.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at SonarLint.VisualStudio.Integration.Vsix.SonarLintIntegrationPackage.<InitializeAsync>d__4.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass16_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__76.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
at Microsoft.VisualStudio.Services.VsTask.GetResult()
```

**Comment by duncanp-sonar** [comment]
@pavel-mikula-sonarsource that dogfood version installed correctly on my machine.
That error message can indicate a corrupt VS MEF cache, or a problem during installation.

Could you try clearing the MEF cache to see if that fixes it? (https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ClearMEFComponentCache will help).

If not, does uninstalling/reinstalling fix the problem.

**Comment by rita-sonarsource** [comment]
Cannot reproduce, doesn't seem to happen anymore.

**Comment by d1820** [comment]
Still happens for me even after running MEF Cache Clear.

```xml
<entry>
    <record>711</record>
    <time>2022/04/11 12:13:52.594</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [SonarLintIntegrationPackage]Source: &apos;SonarLint.2022&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at SonarLint.VisualStudio.Integration.Vsix.SonarLintIntegrationPackage.&lt;InitOnUIThreadAsync&gt;d__4.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at SonarLint.VisualStudio.Integration.Vsix.SonarLintIntegrationPackage.&lt;InitializeAsync&gt;d__3.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__76.MoveNext()</description>
    <guid>{68D6A325-11E8-4790-A4BA-0EDD001FB080}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>
```

The only solution was uninstalling the extension
