### ISSUE TITLE
SL for VS2019 cannot find VCProjectEngine

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonarlint-visualstudio#2853]
I've noticed this under VS2019 debug logs.
I have a clean installation of VS2019 where ONLY workload for .NET desktop is installed:
```
DEBUG: [CFamilyTelemetryManager] Failed to calculate cfamily project types: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.VCProjectEngine, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.VCProjectEngine, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.VcxProject.VcxProjectTypeIndicator.GetProjectTypes()
   at SonarLint.VisualStudio.Integration.Telemetry.CFamilyTelemetryManager.CollectVcxUsage()
   at SonarLint.VisualStudio.Integration.Telemetry.CFamilyTelemetryManager.UpdateTelemetry()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
````

**Comment by duncanp-sonar** [comment]
Thanks for reporting this @pavel-mikula-sonarsource. It's by design - we don't expect all users to have the C++ workload installed, so we handle the case where it isn't. This exception does not prevent other telemetry from being recorded.

Also, it's a debug-level message, which means it will only appear in the output window if the user has set an internal environment variable.
