### ISSUE TITLE
Error initializing Taint Vulnerabilities package

### ISSUE THREAD

**Issue by rita-sonarsource** [SonarSource/sonarlint-visualstudio#2967]
### Description

Some kind of race condition occurs where the connection info considers the server to be in connected mode, yet `sonarQubeService.ServerInfo` property is null. 

![image](https://user-images.githubusercontent.com/60586879/161740037-ac92a2fc-186b-49bf-916b-9e640d56ae10.png)

![image](https://user-images.githubusercontent.com/60586879/161739935-401e344a-df5f-4a72-a9e5-2bfd0bca88d0.png)

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=SonarLint.VisualStudio.IssueVisualization.Security
  StackTrace:
   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintIssuesSynchronizer.IsFeatureSupported() in C:\Projects\sonarlint-visualstudio\src\IssueViz.Security\Taint\TaintIssuesSynchronizer.cs:line 150
```

```
Initializing the telemetry package...
Current VS version:
    Visual Studio Enterprise 2022
    17.1.31911.260
    17.1.0 Preview 1.1
Loaded settings from "C:\Users\Rita\AppData\Roaming\SonarLint for Visual Studio\settings.json".
Finished initializing the telemetry package...
Initializing the daemon package...
[Open in IDE] Creating request listener...
[Open in IDE] Checking availability of port 64120
[Open in IDE] Port 64120 is unavailable
[Open in IDE] Checking availability of port 64121
[Open in IDE] Request listener created successfully. Listening on port 64121.
Finished initializing the daemon package.
Connecting to 'https://sonarcloud.io/'.
Initializing the SonarLint package...
Finishing initializing the SonarLint package
Initializing the notifications package...
Not connected: not checking for notifications
Finished initializing the notifications package
Connected: checking for notifications
Checking for suppressions...
Number of suppressions found: 95
[Taint] Initializing taint issues synchronization package...
[Taint] Failed to synchronize taint vulnerabilities with the connected server: System.NullReferenceException: Object reference not set to an instance of an object.
   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintIssuesSynchronizer.IsFeatureSupported()
   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintIssuesSynchronizer.<SynchronizeWithServer>d__10.MoveNext().
[Taint] Finished initializing taint issues synchronization package.
Connecting to SonarQube server: https://sonarcloud.io/
Connecting to SonarQube server: Validating credentials
Connecting to SonarQube server: Detecting server plugins
   Discovered a supported plugin: Plugin: 'SonarC#', Language(s): 'C#', Installed version: '8.37.0', Minimum version: '5.0'
   Discovered a supported plugin: Plugin: 'SonarVB', Language(s): 'VB.NET', Installed version: '8.37.0', Minimum version: '3.0'
   Discovered a supported plugin: Plugin: 'SonarCFamily', Language(s): 'C++, C', Installed version: '6.32.0', Minimum version: '6.0'
Connecting to SonarQube server: Retrieving projects
Suppressions have been updated. Open documents will be re-analysed.
[Taint] Failed to synchronize taint vulnerabilities with the connected server: System.NullReferenceException: Object reference not set to an instance of an object.
   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintIssuesSynchronizer.IsFeatureSupported()
   at SonarLint.VisualStudio.IssueVisualization.Security.Taint.TaintIssuesSynchronizer.<SynchronizeWithServer>d__10.MoveNext().
Checking for suppressions...
Starting job: "re-analyzing 0 document(s)...". Time: 11:04:11 AM
Finished job "re-analyzing 0 document(s)..." started at 11:04:11 AM. Elapsed time: 18ms
Connecting to SonarQube server: Succeeded
Connecting to SonarQube server: Downloading server settings.
Number of suppressions found: 95
DEBUGONLY: Connect workflow finished, Execution result: Succeeded
Connected to SonarCloud '8.0.0.28085'.
Checking for unbound projects.
No unbound projects were found.
Checking if SonarQube Quality profile has changed.
The Quality Profile for the SonarQube project has changed. Update is required.

```

#### Steps to reproduce:

1. Load sonar-dotnet solution
2. Open the team explorer sonarqube tab while the solution is loading

#### Notes 
Potentially relates to #2826
... or #696 (more likely)

**Comment by rita-sonarsource** [comment]
Fixed by #3152
