### ISSUE TITLE
Connection refused Error on opening a folder with js file. 

### ISSUE THREAD

**Issue by ugras-ergun-sonarsource** [SonarSource/sonarlint-visualstudio#3143]
### Description

Re-opening a bound folder with a js/ts file open can trigger an exception.

### Repro steps

1. Open a Bound Folder with a js file in it.
2. Open the file and wait for analysis. 
3. Close the folder.
4. Open it again immediately.

### Expected behaviour

No error is thrown 

### Actual behaviour 

The following error is thrown

```
Failed to analyze C:\Code\TheAlgorithms\Sorts\MergeSort.js: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:50289
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.EslintBridgeClient.EslintBridgeHttpWrapper.<PostAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.EslintBridgeClient.EslintBridgeClient.<MakeCall>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.EslintBridgeClient.EslintBridgeClient.<InitLinter>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.Analyzer.EslintBridgeAnalyzer.<EnsureEslintBridgeClientIsInitialized>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.Analyzer.EslintBridgeAnalyzer.<Analyze>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.TypeScript.Analyzer.JavaScriptAnalyzer.<ExecuteAnalysis>d__6.MoveNext()
   ```
   

Notes:
* The error is caused because we're killing the process, while an existing http call is still running. For example: opening a folder -> triggering init-linter request -> closing the folder -> triggering closing of the process -> init-linter request fails.
* "Close" should wait until any running calls are done executing.

**Comment by ugras-ergun-sonarsource** [comment]
After investigation, we have found that this error is more likely to happen when you reopen the folder quickly. And If we look at the logs what we see is the failing connection port is the same as the port from the first instance of the eslintbridge. And based on this we have a hypothesis: It takes some time to shut down the eslintbrige process. And we find ourselves in a position where the eslintbridge server is shut down but the process is still running. And because of that instead of starting a new eslintbridge process, we try to use the existing process which is shutting down. And when this fails our retry mechanism fires up a new instance of the process and can analyze the code. 
Our hypothesis is the error is somewhat related to [RequireLinterUpdate method](https://github.com/SonarSource/sonarlint-visualstudio/blob/4f5f5270790d399891840c3e10b6a1d9462af424/src/TypeScript/Analyzer/EslintBridgeAnalyzer.cs#L157) under EslintBridgeAnalyzer.cs.

**Comment by rita-sonarsource** [comment]
Occurs when the init-linter is called before the close call terminates.

![image](https://user-images.githubusercontent.com/60586879/182835506-ca9587dd-1c45-433c-9cd1-d1abe71fdf0b.png)
