### ISSUE TITLE
Analysis executes several times for a single file.

### ISSUE THREAD

**Issue by Kalabaza** [SonarSource/sonarlint-visualstudio#3290]
I'm using SonarLint for a C++ project that uses CLang document formatting, this step is executed after saving the file with the extension [Format document on Save](https://github.com/Elders/VSE-FormatDocumentOnSave). This is with Visual Studio Professional 2022.

The problem is that SonarLint executes as soon as the document is saved, then the extension modifies the document and SonarLint tries to execute the analysis again, but since it is already a process running the new execution is aborted. But this is executed several times in a row (more than 30 times, maybe you have a retry value in some place), which can be seen in the log:

```
Analyzing File.cpp
Execution cancelled.
Finished analyzing File.cpp, analysis time: 0.019s
Aborted analysis of File.cpp, analysis has been re-triggered or has timed-out.
```

Even sometimes and IO error can be seen in the log:
```
Analyzing File.cpp
Failed to analyze File.cpp: System.IO.IOException: The process cannot access the file 'File.cpp' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.VisualStudio.Text.Implementation.TextDocumentFactoryService.OpenFileGuts(String filePath, DateTime& lastModifiedTimeUtc, Int64& fileSize)
   at Microsoft.VisualStudio.Text.Implementation.TextDocumentFactoryService.CreateAndLoadTextDocument(String filePath, IContentType contentType, Boolean attemptUtf8Detection, Boolean allowCompressedStorage, Boolean throwOnInvalidCharactersIfUnknownEncoding, Boolean& characterSubstitutionsOccurred)
   at Microsoft.VisualStudio.Text.Implementation.TextDocumentFactoryService.CreateAndLoadTextDocument(String filePath, IContentType contentType)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyIssueToAnalysisIssueConverter.GetFileContentsOfReportedFiles(Message cFamilyIssue)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.CFamilyIssueToAnalysisIssueConverter.Convert(Message cFamilyIssue, String sqLanguage, ICFamilyRulesConfig rulesConfiguration)
   at SonarLint.VisualStudio.CFamily.SubProcess.MessageHandler.HandleAnalysisIssue(Message message)
   at SonarLint.VisualStudio.CFamily.SubProcess.MessageHandler.HandleMessage(Message message)
   at SonarLint.VisualStudio.CFamily.SubProcess.Protocol.Read(BinaryReader reader, Action`1 handleIssue)
   at SonarLint.VisualStudio.CFamily.Analysis.CLangAnalyzer.<>c__DisplayClass16_0.<ExecuteSubProcess>b__1(StreamReader reader)
   at SonarLint.VisualStudio.CFamily.SubProcess.ProcessRunner.Execute(ProcessRunnerArguments runnerArgs)
   at SonarLint.VisualStudio.CFamily.Analysis.CLangAnalyzer.ExecuteSubProcess(Action`1 handleMessage, IRequest request, IProcessRunner runner, ILogger logger, CancellationToken cancellationToken, IFileSystem fileSystem)
   at SonarLint.VisualStudio.CFamily.Analysis.CLangAnalyzer.CallSubProcess(Action`1 handleMessage, IRequest request, ISonarLintSettings settings, ILogger logger, CancellationToken cancellationToken)
   at SonarLint.VisualStudio.CFamily.Analysis.CLangAnalyzer.RunAnalysis(IRequest request, IIssueConsumer consumer, IAnalysisStatusNotifier statusNotifier, CancellationToken cancellationToken)
```

Plase let me know if you need anymore details to solve this problem.

**Comment by Kalabaza** [comment]
Any update on this issue?

Due to this, I had disabled the SonarQube plugin on my machine, since it's really not working well and it only causes problems.
