### ISSUE TITLE
Investigate JS locking

### ISSUE THREAD

**Issue by rita-sonarsource** [SonarSource/sonarlint-visualstudio#3417]
### Description

```
Initializing the telemetry package...
Loaded settings from "C:\Users\rita.gorokhod\AppData\Roaming\SonarLint for Visual Studio\settings.json".
Current VS version:
    Visual Studio Enterprise 2022
    17.5.33103.201
    17.5.0 Preview 1.0
Finished initializing the telemetry package...
[SecretsAnalyzer] Analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[SecretsAnalyzer] Finished analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js, analysis time: 0.081s
[SecretsAnalyzer] Found 0 issue(s) for C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[JavaScriptAnalyzer] Analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[NodeJSLocator] Checking environment variable SONAR_NODEJS_PATH
[NodeJsLocator] Environment variable is not set
[NodeJsLocator] Found compatible Node.js version: 19.1.0. Path: C:\Program Files\nodejs\node.exe
[eslint-bridge] Started eslint-bridge process. Process id: 30008
[SecretsAnalyzer] Analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[SecretsAnalyzer] Finished analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js, analysis time: 0s
[SecretsAnalyzer] Found 0 issue(s) for C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[JavaScriptAnalyzer] Analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[NodeJSLocator] Checking environment variable SONAR_NODEJS_PATH
[NodeJsLocator] Environment variable is not set
[NodeJsLocator] Found compatible Node.js version: 19.1.0. Path: C:\Program Files\nodejs\node.exe
[eslint-bridge] Started eslint-bridge process. Process id: 35756
[SecretsAnalyzer] Analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[SecretsAnalyzer] Finished analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js, analysis time: 0.001s
[SecretsAnalyzer] Found 0 issue(s) for C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[JavaScriptAnalyzer] Analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
Initializing the daemon package...
Finished initializing the daemon package.
[Open in IDE] Creating request listener...
[Open in IDE] Checking availability of port 64120
[Open in IDE] Request listener created successfully. Listening on port 64120.
Initializing the SonarLint package...
Finishing initializing the SonarLint package
Initializing the notifications package...
Not connected: not checking for notifications
Finished initializing the notifications package
[SecretsAnalyzer] Analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[SecretsAnalyzer] Finished analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js, analysis time: 0s
[SecretsAnalyzer] Found 0 issue(s) for C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[JavaScriptAnalyzer] Analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[SecretsAnalyzer] Analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[SecretsAnalyzer] Finished analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js, analysis time: 0s
[SecretsAnalyzer] Found 0 issue(s) for C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
[JavaScriptAnalyzer] Analyzing C:\projects\sonarlint-visualstudio-sampleprojects\standalone\vs2022\NormalSolution\Cpp_WindowsProject_VS2022\JavaScript\JavaScript1.js
```

**Comment by rita-sonarsource** [comment]
Closing as dup, same as https://github.com/SonarSource/sonarlint-visualstudio/issues/3230.
Enabling debug logs shows an error
```
DEBUG: eslint-bridge node error] [process id: 24764] : C:\USERS\RITA.GOROKHOD\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_8FADB6D5EXP\EXTENSIONS\SonarSource\SLAF\6.11.0.0\ts\node_modules\toidentifier\index.js:26
DEBUG: eslint-bridge node error] [process id: 24764] :     .split(' ')
DEBUG: eslint-bridge node error] [process id: 24764] :      ^
DEBUG: eslint-bridge node error] [process id: 24764] : TypeError: Cannot read properties of undefined (reading 'split')
DEBUG: eslint-bridge node error] [process id: 24764] :     at toIdentifier (C:\USERS\RITA.GOROKHOD\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_8FADB6D5EXP\EXTENSIONS\SonarSource\SLAF\6.11.0.0\ts\node_modules\toidentifier\index.js:26:6)
DEBUG: eslint-bridge node error] [process id: 24764] :     at forEachCode (C:\USERS\RITA.GOROKHOD\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_8FADB6D5EXP\EXTENSIONS\SonarSource\SLAF\6.11.0.0\ts\node_modules\send\node_modules\http-errors\index.js:245:16)
DEBUG: eslint-bridge node error] [process id: 24764] :     at Array.forEach (<anonymous>)
DEBUG: eslint-bridge node error] [process id: 24764] :     at populateConstructorExports (C:\USERS\RITA.GOROKHOD\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_8FADB6D5EXP\EXTENSIONS\SonarSource\SLAF\6.11.0.0\ts\node_modules\send\node_modules\http-errors\index.js:243:9)
DEBUG: eslint-bridge node error] [process id: 24764] :     at Object.<anonymous> (C:\USERS\RITA.GOROKHOD\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_8FADB6D5EXP\EXTENSIONS\SonarSource\SLAF\6.11.0.0\ts\node_modules\send\node_modules\http-errors\index.js:30:1)
DEBUG: eslint-bridge node error] [process id: 24764] :     at Module._compile (node:internal/modules/cjs/loader:1205:14)
DEBUG: eslint-bridge node error] [process id: 24764] :     at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
DEBUG: eslint-bridge node error] [process id: 24764] :     at Module.load (node:internal/modules/cjs/loader:1068:32)
DEBUG: eslint-bridge node error] [process id: 24764] :     at Module._load (node:internal/modules/cjs/loader:909:12)
DEBUG: eslint-bridge node error] [process id: 24764] :     at Module.require (node:internal/modules/cjs/loader:1092:19)
DEBUG: eslint-bridge node error] [process id: 24764] : Node.js v19.1.0
```
