### ISSUE TITLE
AD0001 errors from SonarAnalyzer.CSharp when opening SLVS solution

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#3476]
### Description

Open SLVS solution in a VS instance with SLVS installed causes the Sonar C# analyzer to raise thousands of AD0001 errors.

See also: #2926 

### Repro
SLVS 6.11.0 installed
VS configuration: full solution analysis, analyze in external process (-> .NET Fx)

* Sync SLVS solution to [commit fbeb97d6702732b4191b4ad5ce4ab765b35293ae](https://github.com/SonarSource/sonarlint-visualstudio/commit/fbeb97d6702732b4191b4ad5ce4ab765b35293ae) (should probably fail with any commit where SLVS is using a SonarAnalyzer.CSharp version other than v8.50).
* Open SLVS

### Expected results
* no AD0001 from SonarAnalyzer.CSharp.

### Actual results
Thousands of errors:
![image](https://user-images.githubusercontent.com/10757559/208422923-680bdcad-6aac-4544-855a-e6f00802936b.png)

#### Loaded modules
VS loads a set of v8.50 analyzer assemblies from the extension.
It also loads v8.49 of `SonarAnalyzer.CSharp.dll`, presumably from the NuGet package (?) 
![image](https://user-images.githubusercontent.com/10757559/208423557-88fa0349-8062-4e91-8b81-32efddbd3bb7.png)

#### Example call stack
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.BooleanLiteralUnnecessary' threw an exception of type 'System.TypeLoadException' with message 'Method 'AssignmentLeft' in type 'SonarAnalyzer.Helpers.Facade.CSharpSyntaxFacade' from assembly 'SonarAnalyzer.CSharp, Version=8.49.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244' does not have an implementation.'.
Exception occurred with following context:
Compilation: SonarLint.2022
SyntaxTree: D:\repos\sq\slvs\src\Integration.Vsix\Commands\ConnectedModeMenu\ManageConnectionsCommand.cs
SyntaxNode: this.teamExplorer != null [BinaryExpressionSyntax]@[1658..1683) (44,25)-(44,50)

System.TypeLoadException: Method 'AssignmentLeft' in type 'SonarAnalyzer.Helpers.Facade.CSharpSyntaxFacade' from assembly 'SonarAnalyzer.CSharp, Version=8.49.0.0, Culture=neutral, PublicKeyToken=c5b62af9de6d7244' does not have an implementation.
   at SonarAnalyzer.Helpers.CSharpFacade.<>c.<.cctor>b__28_3()
   at System.Lazy`1.CreateValue()
   at SonarAnalyzer.Rules.BooleanLiteralUnnecessaryBase`2.CheckForNullabilityAndBooleanConstantsReport(TBinaryExpression binaryExpression, SyntaxNodeAnalysisContext context, Boolean reportOnTrue)
   at SonarAnalyzer.Rules.BooleanLiteralUnnecessaryBase`2.CheckNotEquals(SyntaxNodeAnalysisContext context)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass1_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at System.Lazy`1.get_Value()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
   at SonarAnalyzer.Helpers.Trackers.PropertyAccessTracker`1.CreateContext(SyntaxNodeAnalysisContext context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at SonarAnalyzer.Helpers.SyntaxTrackerBase`2.<>c__DisplayClass4_0.<Track>g__TrackAndReportIfNecessary|1(SyntaxNodeAnalysisContext c)
   at System.Lazy`1.get_Value()
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass3_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at SonarAnalyzer.Helpers.Trackers.FieldAccessTracker`1.CreateContext(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
   at SonarAnalyzer.Helpers.SyntaxTrackerBase`2.<>c__DisplayClass4_0.<Track>g__TrackAndReportIfNecessary|1(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass3_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: S1125	Integration.Vsix		1	Active
```

### Notes
The SLVS solution references the Roslyn Sonar analyzers as NuGet packages, and also has some non-standard MSBuild tweaks to make sure the correct assemblies are embedded in the SLVS VSIX.

TODO: check whether this problem repros for other solutions.
UPDATE: the issue doesn't seem to occur with other "normal" projects, even if they reference the Sonar analyzer assemblies as NuGet packages.
Note: if the SLVS solution has been loaded, then other solutions may show issue (i.e. that instance is VS has been corrupted by loading SLVS.sln). Other solutions load correctly in a new instance of VS.

[AD0001Repro.zip](https://github.com/SonarSource/sonarlint-visualstudio/files/10259391/AD0001Repro.zip)

**Comment by duncanp-sonar** [comment]
### Additional Scenario (1) - SLVS installed, non-SLVS project, no NuGet references -> ok
SLVS 6.11.0 installed
VS configuration: full solution analysis, analysis in external process

* new C# console app, no Sonar.Analyzer.* NuGet refs
* solution analysis runs
No AD0001 errors

Investigation:
Attached debugger. All SonarAnalyzer.* assemblies have the same version (v8.50)

![Modules_SLVSOnly__binary_versions_match](https://user-images.githubusercontent.com/10757559/208425841-5154aaf8-ddcc-4457-a087-c1b6c7ba135e.png)

**Comment by duncanp-sonar** [comment]
### Additional Scenario (2) - SLVS installed, non-SLVS project, NuGet ref to SonarAnalyzer.CSharp -> ok
SLVS 6.11.0 installed
VS configuration: full solution analysis, analysis in external process

* new C# console app.
* added ref to SonarAnalyzer.CSharp v8.49

No AD0001 errors

#### Investigation:
Attached debugger. Two sets of SonarAnalyzer.* assemblies have been loaded - v8.49 and v8.50.

![Modules_SLVS16_1_and_NuGet_5_49_two set of binaries loaded](https://user-images.githubusercontent.com/10757559/208426019-8c00334c-d116-49b5-94fc-947d9687800b.png)

**Comment by duncanp-sonar** [comment]
Similar issue occurring with Microsoft Roslyn analyzers when opening the SLVS solution:
SLVS 6.11.0 installed
VS configuration: full solution analysis, analysis in external process (.NET Fx)

![image](https://user-images.githubusercontent.com/10757559/208433224-9a987535-258e-49f1-9ad8-9b2ec3400e0d.png)

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpImmutableObjectMethodAnalyzer' threw an exception of type 'System.TypeLoadException' with message 'Could not load type 'Microsoft.CodeAnalysis.Analyzers.ITypeSymbolExtensions' from assembly 'Microsoft.CodeAnalysis.Analyzers, Version=2.9.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.'.
Exception occurred with following context:
Compilation: SonarLint.2022
SyntaxTree: D:\repos\sq\slvs\src\Integration.Vsix\Native\INativeMethods.cs
SyntaxNode: NativeMethodDeclarations.GetAncestor ... [InvocationExpressionSyntax]@[1761..1810) (48,62)-(48,111)

System.TypeLoadException: Could not load type 'Microsoft.CodeAnalysis.Analyzers.ITypeSymbolExtensions' from assembly 'Microsoft.CodeAnalysis.Analyzers, Version=2.9.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpImmutableObjectMethodAnalyzer.AnalyzeInvocationForIgnoredReturnValue(SyntaxNodeAnalysisContext context, ImmutableArray`1 immutableTypeSymbols)
   at Microsoft.CodeAnalysis.CSharp.Analyzers.CSharpImmutableObjectMethodAnalyzer.<>c__DisplayClass16_0.<Initialize>b__2(SyntaxNodeAnalysisContext sc)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: RS1014	Integration.Vsix		1	Active
```

![image](https://user-images.githubusercontent.com/10757559/208433796-39675406-bfaa-47b3-b130-77ed9dfa5853.png)

**Comment by duncanp-sonar** [comment]
### Additional scenario (3) - as scenario (2), with some of the VSIX-related SLVS changes -> ok
SLVS 6.11.0 installed
VS configuration: full solution analysis, analysis in external process

* new C# console app.
* added ref to SonarAnalyzer.CSharp v8.49
* project file changes copied from SLVS related to updating embedding the analyzer assemblies to the VSIX.
 
No AD0001 errors
