### ISSUE TITLE
[Infra] Assertions and logged errors when opening Connected Mode project

### ISSUE THREAD

**Issue by duncanp-lseg** [SonarSource/sonarlint-visualstudio#4245]
### Description

Repro: open a bound project.

There are no obvious functional problems i.e. Connected Mode seems to work as expected, but errors are logged in the Output window.

Guesswork: it could be a event timing/ordering issue, relating to events raised by the `ActiveSolutionBoundTracker`.
The taint and suppressions are handling an event and expecting the server to be connected, but the connection has not yet been established. However, a later event fires at which point the taint issues and suppressions are fetched again, this time successfully -> no obvious functional impact.

#### Errors - info-level logging
![image](https://github.com/SonarSource/sonarlint-visualstudio/assets/10757559/e96d893a-2ab1-42c9-9f28-fe961c28d357)

#### Errors - verbose logging
![image](https://github.com/SonarSource/sonarlint-visualstudio/assets/10757559/29a950b6-6567-439a-bf16-c4219014c8ef)

#### Assertion
![image](https://github.com/SonarSource/sonarlint-visualstudio/assets/10757559/51471b61-c343-4050-bea5-07ebf6c84088)

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Not expecting GetMatchedBranch to be called unless we are in Connected Mode

   at SonarLint.VisualStudio.ConnectedMode.BranchMatcher.<GetMatchingBranch>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at SonarLint.VisualStudio.ConnectedMode.BranchMatcher.GetMatchingBranch(String projectKey, IRepository gitRepo, CancellationToken token)
   at SonarLint.VisualStudio.ConnectedMode.ServerBranchProvider.<CalculateMatchingBranchAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at SonarLint.VisualStudio.ConnectedMode.ServerBranchProvider.CalculateMatchingBranchAsync(BindingConfiguration config, CancellationToken token)
   at SonarLint.VisualStudio.ConnectedMode.ServerBranchProvider.<GetServerBranchNameAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at SonarLint.VisualStudio.ConnectedMode.ServerBranchProvider.GetServerBranchNameAsync(CancellationToken token)
   at SonarLint.VisualStudio.ConnectedMode.StatefulServerBranchProvider.<>c__DisplayClass10_0.<DoGetServerBranchNameAsync>b__0()
   at SonarLint.VisualStudio.Infrastructure.VS.ThreadHandling.<>c__DisplayClass6_0`1.<<RunOnBackgroundThread>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at SonarLint.VisualStudio.Infrastructure.VS.ThreadHandling.<>c__DisplayClass6_0`1.<RunOnBackgroundThread>b__0()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.ExecuteJob[T](Func`1 asyncMethod, JoinableTask job)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync[T](Func`1 asyncMethod, Boolean synchronouslyBlocking, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.RunAsync[T](Func`1 asyncMethod)
   at SonarLint.VisualStudio.Infrastructure.VS.ThreadHandling.<RunOnBackgroundThread>d__6`1.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at SonarLint.VisualStudio.Infrastructure.VS.ThreadHandling.RunOnBackgroundThread[T](Func`1 asyncMethod)
   at SonarLint.VisualStudio.ConnectedMode.StatefulServerBranchProvider.DoGetServerBranchNameAsync(CancellationToken token)
   at SonarLint.VisualStudio.ConnectedMode.StatefulServerBranchProvider.<GetServerBranchNameAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at SonarLint.VisualStudio.ConnectedMode.StatefulServerBranchProvider.GetServerBranchNameAsync(CancellationToken token)
   at SonarLint.VisualStudio.ConnectedMode.ServerQueryInfoProvider.<GetProjectKeyAndBranchAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at SonarLint.VisualStudio.ConnectedMode.ServerQueryInfoProvider.GetProjectKeyAndBranchAsync(CancellationToken token)
   at SonarLint.VisualStudio.ConnectedMode.Suppressions.SuppressionIssueStoreUpdater.<UpdateAllServerSuppressionsAsync>d__8.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by pavel-mikula-sonarsource** [comment]
Moved to [SLVS-2204](https://sonarsource.atlassian.net/browse/SLVS-2204)

[SLVS-2204]: https://sonarsource.atlassian.net/browse/SLVS-2204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
