### ISSUE TITLE
Error when using ssh to connect to VSCode Server and vscode.git is not set up, before extension loads

### ISSUE THREAD

**Issue by Jona898** [SonarSource/sonarlint-visualstudio#4330]
I am running SonarLint with Sonarcloud in VS Code Server.
I use a Linux VM-Ware virtual Machine and connect via ssh from vscode in Windows.

Sometimes when i startup this extension seems to be loaded bevore the vscode.git is connected and it doesn't show any issues. I need to reload window and then the extension works.

Output in Output/SonarLint:
```
Executing /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/jre/17.0.7-linux-x86_64.tar/bin/java -jar /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/server/sonarlint-ls.jar -stdio -analyzers /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/analyzers/sonargo.jar /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/analyzers/sonarjava.jar /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/analyzers/sonarjs.jar /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/analyzers/sonarphp.jar /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/analyzers/sonarpython.jar /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/analyzers/sonarhtml.jar /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/analyzers/sonarxml.jar /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/analyzers/sonarcfamily.jar /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/analyzers/sonartext.jar /home/dev/.vscode-server/extensions/sonarsource.sonarlint-vscode-3.18.0-linux-x64/analyzers/sonariac.jar
Exception occurred while initializing the Git API: Error: Extension 'vscode.git' is not known or not activated
[Error - 10:26:23.423] Unable to check if file file:///home/dev/Documents/REPOSITORY/.vscode/settings.json is SCM ignored
[Error - 10:26:23.434] org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request sonarlint/isIgnoredByScm failed with message: Extension 'vscode.git' is not known or not activated
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

[Info  - 10:26:23.930] Started embedded server on port 64120
[Info  - 10:26:27.183] Downloaded plugin list in 90ms
[Info  - 10:26:27.184] [SYNC] Synchronizing analyzer configuration for project 'PROJECTNAME'
[Info  - 10:26:27.268] Downloaded settings in 80ms
[Info  - 10:26:27.412] [SYNC] Fetching rule set for language 'apex' from profile 'ProfileConfiguration'
[Info  - 10:26:27.571] [SYNC] Fetching rule set for language 'c' from profile 'ProfileConfiguration'
[Info  - 10:26:27.734] [SYNC] Fetching rule set for language 'cloudformation' from profile 'ProfileConfiguration'
[Info  - 10:26:27.828] [SYNC] Fetching rule set for language 'cpp' from profile 'ProfileConfiguration'
[Info  - 10:26:28.432] [SYNC] Fetching rule set for language 'css' from profile 'ProfileConfiguration'
[Info  - 10:26:28.517] [SYNC] Fetching rule set for language 'docker' from profile 'ProfileConfiguration'
[Info  - 10:26:28.637] [SYNC] Fetching rule set for language 'go' from profile 'ProfileConfiguration'
[Info  - 10:26:28.733] [SYNC] Fetching rule set for language 'java' from profile 'ProfileConfiguration'
[Info  - 10:26:29.494] [SYNC] Fetching rule set for language 'js' from profile 'ProfileConfiguration'
[Info  - 10:26:29.727] [SYNC] Fetching rule set for language 'kubernetes' from profile 'ProfileConfiguration'
[Info  - 10:26:29.839] [SYNC] Fetching rule set for language 'php' from profile 'ProfileConfiguration'
[Info  - 10:26:30.010] [SYNC] Fetching rule set for language 'plsql' from profile 'ProfileConfiguration'
[Info  - 10:26:30.146] [SYNC] Fetching rule set for language 'py' from profile 'ProfileConfiguration'
[Info  - 10:26:30.535] [SYNC] Fetching rule set for language 'secrets' from profile 'ProfileConfiguration'
[Info  - 10:26:30.615] [SYNC] Fetching rule set for language 'terraform' from profile 'ProfileConfiguration'
[Info  - 10:26:30.747] [SYNC] Fetching rule set for language 'ts' from profile 'AXwxRvajf-ProfileConfiguration'
[Info  - 10:26:30.944] [SYNC] Fetching rule set for language 'web' from profile 'ProfileConfiguration'
[Info  - 10:26:31.090] [SYNC] Fetching rule set for language 'xml' from profile 'ProfileConfiguration'
[Info  - 10:26:31.192] [SYNC] Fetching rule set for language 'yaml' from profile 'ProfileConfiguration'
[Info  - 10:26:31.291] [SYNC] Synchronizing project branches for project 'PROJECTNAME'
```

**Comment by duncanp-sonar** [comment]
@Jona898 please create a thread in the [Community Forum](https://community.sonarsource.com/c/sl/vs-code/36), as requested in the new issue template for this repo.

Also, it looks like your question relates to `Visual Studio Code` rather than `Visual Studio`. The link above is to the VS Code-specific forum group.
