### ISSUE TITLE
VS 2022 17.7.6 throw an error on startup after updating SonarLint to 7.4.0.80741 

### ISSUE THREAD

**Issue by NDomergue** [SonarSource/sonarlint-visualstudio#5034]
Here is the message I get when opening Visual Studio after the update.

![image.png](https://github.com/SonarSource/sonarlint-visualstudio/assets/22598483/258e49bc-003b-48aa-858e-682be76e1383)

And here is the log : 

```
  <entry>
    <record>546</record>
    <time>2023/11/21 15:59:52.696</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [SonarLintIntegrationPackage]Source: &apos;SonarLint.2022&apos; Description: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SonarLint.VisualStudio.Integration.Vsix.SonarLintIntegrationPackage.<InitOnUIThreadAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SonarLint.VisualStudio.Integration.Vsix.SonarLintIntegrationPackage.<InitializeAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)</description>
    <guid>{68D6A325-11E8-4790-A4BA-0EDD001FB080}</guid>
    <hr>0x80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by georgii-borovinskikh-sonarsource** [comment]
Hello @NDomergue. Thank you for reporting this issue.

We would like to ask you to open a thread on our community forum: https://community.sonarsource.com/c/sl/visual-studio/35

Please provide more information about your problem there (how often does it happen, do you need to do anything special to trigger it, etc.).

Thank you.

**Comment by georgii-borovinskikh-sonarsource** [comment]
Hi. I'm not saying this is what happened in your case, but one example could be MEF-cache corruption, which happens to us sometimes. We, however, only get it on the experimental instance of the VS, but we get it more often than normal users since we reinstall different versions of the extension all the time while developing.
