### ISSUE TITLE
System.ArgumentException : An item with the same key has already been added.

### ISSUE THREAD

**Issue by kinloongTong** [SonarSource/sonarlint-visualstudio#507]
### Description

An error occurred when use Fix all occurrences in: Document

### Repro steps

Please provide the steps required to reproduce the problem

1.  use Fix all occurrences in: Document

2. see attachment

### Expected behavior

Replace Or with OrElse in the document

### Actual behavior

Error occurred. 

### Known workarounds

manually replace.

### Related information

* SonarLint for VS Version 3.8.2823
* Visual Studio Enterpricese 2017 Version 4.7.02556
* SonarQube server version 6.7.1 (build 35068)
* Languages in your solution (VB.Net)

###Exception Stack
System.ArgumentException : An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key,TValue value,Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source,Func`2 keySelector,Func`2 elementSelector,IEqualityComparer`1 comparer)
   at async SonarAnalyzer.Common.DocumentBasedFixAllProvider.GetFixedDocumentAsync(<Unknown Parameters>)
   at async SonarAnalyzer.Common.DocumentBasedFixAllProvider.<>c__DisplayClass8_0.<GetFixAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.FixAllGetFixesService.GetFixAllOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsAsync(<Unknown Parameters>)
   at Roslyn.Utilities.TaskExtensions.WaitAndGetResult_CanCallOnBackground[T](Task`1 task,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.InvokeWorker(Func`1 getFromDocument,IProgressTracker progressTracker,CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.<>c__DisplayClass18_0.<InvokeCore>b__0()
   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformAction(IExtensionManager extensionManager,Object extension,Action action)
![2018-01-24 3 _li](https://user-images.githubusercontent.com/30917733/35319745-1f9bbe02-011c-11e8-90f3-53b10c58eeec.jpg)

**Comment by Evangelink** [comment]
Hi @kinloongTong,

Thanks for reporting this issue. 
I am moving it to the right repository and closing this one (see SonarSource/sonar-csharp#1109)

**Comment by kinloongTong** [comment]
Thanks!
