### ISSUE TITLE
Unable to collect C/C++ configuration: System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by k-brac** [SonarSource/sonarlint-visualstudio#648]
### Description

Visual Studio 15.7.2
SonarLint 4.0.0.3479
For a solution generated with cmake 3.11.1 using only C++
For every header file I open I have the following error in the output panel of SonarLint:

> Unable to collect C/C++ configuration: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Microsoft.VisualStudio.ProjectSystem.ProjectException: The "ConfigurationCustomBuildTool" rule is missing the "AdditionalIncludeDirectories" property.
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorUtilities.ThrowProjectExceptionHelper(Exception innerException, String unformattedMessage, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorUtilities.ThrowProjectException(String message, Object arg0, Object arg1)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCRulePropertyStorage.<>c__DisplayClass5_0.<<GetEvaluatedPropertyValue>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.ApartmentMarshaler.<>c__DisplayClass9_0`1.<<Invoke>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.ApartmentMarshaler.Invoke[TResult](Func`1 method)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCRulePropertyStorage.GetEvaluatedPropertyValue(String propertyName)
   at Microsoft.VisualStudio.Project.VisualC.VCProjectEngine.VCToolBase.Microsoft.VisualStudio.VCProjectEngine.IVCRulePropertyStorage.GetEvaluatedPropertyValue(String propertyName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CallSite.Target(Closure , CallSite , MethodInfo , Object , Object[] )
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.FileConfig.GetEvaluatedPropertyValue(Object fileTool, String propertyName)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.FileConfig.TryGet(ProjectItem projectItem, String absoluteFilePath)
   at SonarLint.VisualStudio.Integration.Vsix.CFamily.TryGetConfig(ILogger logger, ProjectItem projectItem, String absoluteFilePath, String& sqLanguage)

### Repro steps

I just installed it

### Expected behavior
I expected the plugin to provide an analysis without dying

### Actual behavior

Nothing except the stacktrace

### Known workarounds

None

### Related information

* SonarLint for VS Version : 4.0.0.3479
* Visual Studio Version (e.g. Professional v15.4.1) : 15.7.2
* SonarQube server version : no server
* Languages in your solution (C#, VB.Net, Javascript, C, C++) : C++ only

**Comment by duncanp-sonar** [comment]
@k-brac Thanks for reporting the issue.

Could you confirm that the exception message appears for every file type (_.h and .cxx_) please?

I can repro the problem for _.h_ files using _cmake_ 3.11.1, [this sample](https://github.com/cognitivewaves/CMake-VisualStudio-Example) cmake project, and a solution generated using the command:
`cmake.exe -G "Visual Studio 15 2017"`
However, _cxx_ files are analysed correctly.

**Comment by k-brac** [comment]
I just installed version 4.1.0.3539
It works for *.cpp files but not for headers

**Comment by duncanp-sonar** [comment]
Thanks for the confirmation.
FYI I've checked with our C++ team and currently header files cannot be analysed by SonarLint (we can't collect all of the configuration information we need to analyse them correctly).

I'll change SonarLint to skip analysis of header files.
