### ISSUE TITLE
SonarLint crashes VS when opening a solution

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#649]
### Repro steps
1. Open VS
2. Open an existing C# solution (I was just using a simple console app).

## Expected
Solution opens correctly

## Actual
Crash -> VS terminates.

Exception:
SonarLint.VisualStudio.Integration.dll!SonarLint.VisualStudio.Integration.ProjectsRuleSetProvider.OnActiveSolutionChanged(object sender, SonarLint.VisualStudio.Integration.ActiveSolutionChangedEventArgs e) Line 129	C#

System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at SonarLint.VisualStudio.Integration.ProjectsRuleSetProvider.<BuildCacheAsync>d__14.MoveNext() in C:\agent_duncanpsonar\_work\1\s\src\Integration\MefServices\ProjectsRuleSetProvider.cs:line 152
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at SonarLint.VisualStudio.Integration.ProjectsRuleSetProvider.<OnActiveSolutionChanged>d__12.MoveNext() in C:\agent_duncanpsonar\_work\1\s\src\Integration\MefServices\ProjectsRuleSetProvider.cs:line 129

### Notes
Potentially a timing issue in the construction of _ProjectsRuleSetProvider_: the cache is built when the class is constructed, and refresh when the active solution changes. When running under the debugger in the experimental hive (which probably exaggerates the timing issues because the extension runs much slower), the _BuildCache_ method is still running from the call in the constructor when the _OnActiveSolution_ changed method fires and triggers _BuildCache_ on another thread.

### Related information

* SonarLint for VS Version: ??? (I thought I had 4.0.0.3479 installed, but the file in the call stack doesn't appear to exist in that version - this might not be an issue in the latest version)
* Visual Studio Version (e.g. Enterprise 15.7.2)
* Languages in your solution: C#

**Comment by duncanp-sonar** [comment]
I'm closing this issue: the class _ProjectsRuleSetProvider_ does not exist in the 4.0.0.3479 version of the repo. I was seeing this crash when running an experimental version of VS, so I guess the experimental hive must have been using an older version of SonarLint.
