### ISSUE TITLE
Connection failure during build

### ISSUE THREAD

**Issue by sachinsu** [SonarSource/sonarlint-visualstudio#714]
### Description

While running "Analyze" -> "Run code analysis on Solution", below error id logged in sonarlint output window. 

Initializing the daemon package...
Starting the daemon...
Running C:\SonarLint for Visual Studio\sonarlint-daemon-3.4.0.1536-windows\jre\bin\java.exe
Daemon started successfully.
Finished initializing the daemon package.
15:07:36.404 [main] INFO  o.s.d.Daemon - Starting server on port 8051
Checking for unbound projects.
No unbound projects were found.
Checking if SonarQube Quality profile has changed.
Quality Profile is up-to-date.
15:07:41.620 [main] ERROR o.s.d.Daemon - Error running daemon
java.io.IOException: Failed to bind
       at io.grpc.netty.NettyServer.start(NettyServer.java:197) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.grpc.internal.ServerImpl.start(ServerImpl.java:153) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at org.sonarlint.daemon.Daemon.start(Daemon.java:81) [sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at org.sonarlint.daemon.Daemon.main(Daemon.java:60) [sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
Caused by: java.net.BindException: Address already in use: bind
       at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_121]
       at sun.nio.ch.Net.bind(Net.java:433) ~[na:1.8.0_121]
       at sun.nio.ch.Net.bind(Net.java:425) ~[na:1.8.0_121]
       at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223) ~[na:1.8.0_121]
       at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) ~[sonarlint-daemon-3.4.0.1536.jar:3.4.0.1536]
       at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]

* SonarLint for VS Version - 4.1.0.3539
* Visual Studio 2015
* Languages in your solution - C#

**Comment by duncanp-sonar** [comment]
@sachinsu 
Check that there isn't a previous instance of the daemon still running (or just reboot, then re-open Visual Studio).
If the error still occurs after reboot, check whether the port 8051 is being used by any other applications running on your machine.

Alternatively, if you don't need to analyzer C++ or JavaScript code, you can turn off the daemon (_Tools_, _Options_, _SonarLint for Visual Studio_, ...)
