### ISSUE TITLE
Error AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.ImplementIDisposableCorrectly' threw an exception of type 'System.ArgumentException' with message 'SyntaxTree is not part of the compilation

### ISSUE THREAD

**Issue by GuidoDeVriesWigo4It** [SonarSource/sonarlint-visualstudio#737]
### Description

I have a SonarQube server running and Sonarlint in connected mode. SonarQube reports the S2931 error (Classes with "IDisposable" members or native resources should implement "IDisposable"), while locally this error does not show. When I navigate to the IDisposable class that is references, the following error is shown:

Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'SonarAnalyzer.Rules.CSharp.ImplementIDisposableCorrectly' threw an exception of type 'System.ArgumentException' with message 'SyntaxTree is not part of the compilation
Parameter name: syntaxTree'.	CompositeUI.WPF		1	Active	Analyzer 'SonarAnalyzer.Rules.CSharp.ImplementIDisposableCorrectly' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.Practices.CompositeUI.WPF
SyntaxTree: D:\CompositeUI.WPF\ApplicationShellApplication.cs
SyntaxNode: public abstract class ApplicationShellApplication ... [ClassDeclarationSyntax]@[454..1091) (15,1)-(35,2)

System.ArgumentException: SyntaxTree is not part of the compilation
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at SonarAnalyzer.Helpers.SemanticModelHelper.GetSyntaxTreeSemanticModel(SemanticModel model, SyntaxNode node)
   at SonarAnalyzer.Rules.CSharp.ImplementIDisposableCorrectly.DisposableChecker.<HasVirtualDisposeBool>b__17_3(SyntaxNode r)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at SonarAnalyzer.Rules.CSharp.ImplementIDisposableCorrectly.DisposableChecker.HasVirtualDisposeBool(INamedTypeSymbol typeSymbol)
   at SonarAnalyzer.Rules.CSharp.ImplementIDisposableCorrectly.DisposableChecker.GetIssueLocations()
   at SonarAnalyzer.Rules.CSharp.ImplementIDisposableCorrectly.<>c.<Initialize>b__7_0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.DiagnosticAnalyzerContextHelper.<>c__DisplayClass0_0`1.<RegisterSyntaxNodeActionInNonGenerated>b__0(SyntaxNodeAnalysisContext c)
   at SonarAnalyzer.Helpers.SonarAnalysisContext.<>c__DisplayClass21_0`1.<RegisterContextAction>b__0(TContext c)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__44`1.<ExecuteSyntaxNodeAction>b__44_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.

### Repro steps

1. Create a non IDisposable class that references a class that implements IDisposable. 

### Expected behavior

The exact same warning that SonarQube reports. 

### Actual behavior

Not an error at all, until I navigate to the referenced class. Then the error mentioned above is shown in the Error window.

### Related information

* SonarLint for VS Version: 4.4
* Visual Studio Version: VS2017 Enterprise 
* SonarQube server version: 2018.120
* Languages in your solution: C#

**Comment by Evangelink** [comment]
Hi @GuidoDeVriesWigo4It,

Thanks for the feedback. We are aware and already worked on fixing this issue, see [here](https://github.com/SonarSource/sonar-csharp/issues/1804).

Cheers,
Amaury
